web:
  name: 'gprc-server'
  mode: 'dev'
  port: ':50031'
  crtFile: 'certs/server.pem'
  keyFile: 'certs/server.key'
  caFile: 'certs/ca.crt'
mysql:
  host: localhost
  port: 3306
  user: 'root'
  password: 'password'
  dbname: 'grpc'
grpc:
  address: ':50051'
prometheus:
  address: ':9092'
