web:
  name: 'gprc-up'
  mode: 'dev'
  port: '50051'
  crtFile: 'certs/server.pem'
  keyFile: 'certs/server.key'
mysql:
  host: localhost
  port: 3306
  user: 'root'
  password: 'password'
  dbname: 'grpc'
grpc:
  address: 'localhost:50051'
